# Generated by Django 3.2.19 on 2023-06-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=16, verbose_name='代码')),
                ('name', models.CharField(max_length=32, verbose_name='股票名称')),
                ('trade_date', models.CharField(max_length=32, verbose_name='交易日期')),
                ('open', models.FloatField(verbose_name='当日开盘价')),
                ('close', models.FloatField(verbose_name='当日收盘价')),
                ('high', models.FloatField(verbose_name='当日最高价')),
                ('low', models.FloatField(verbose_name='当日最低价')),
                ('change', models.FloatField(verbose_name='涨跌额')),
                ('pct_chg', models.FloatField(verbose_name='涨跌幅')),
                ('vol', models.FloatField(verbose_name='成交量（手）')),
                ('amount', models.FloatField(verbose_name='成交额（千元）')),
                ('turnover_rate', models.FloatField(verbose_name='换手率（%）')),
                ('pre_close', models.FloatField(verbose_name='昨收价(前复权)')),
                ('PE_TTM', models.FloatField(verbose_name='PE_TTM')),
                ('PB', models.FloatField(verbose_name='PB')),
                ('float_share', models.FloatField(verbose_name='流通股本(万股)')),
                ('circ_mv', models.FloatField(verbose_name='流通市值（万元）')),
                ('total_share', models.FloatField(verbose_name='总股本 （万股）')),
                ('total_mv', models.FloatField(verbose_name='总市值 （万元）')),
            ],
        ),
    ]
