# Generated by Django 3.2.19 on 2023-06-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeCompare',
        ),
    ]
