# Generated by Django 3.2.19 on 2023-06-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_cashflow_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=16, verbose_name='代码')),
                ('name', models.CharField(max_length=32, verbose_name='股票名称')),
                ('list_date', models.DateField(blank=True, null=True, verbose_name='上市日期')),
                ('industry', models.CharField(blank=True, max_length=1000, null=True, verbose_name='所属行业')),
                ('market', models.CharField(blank=True, max_length=1000, null=True, verbose_name='市场类型（主板/创业板/科创板/CDR）')),
                ('delist_date', models.DateField(blank=True, null=True, verbose_name='退市日期')),
            ],
        ),
        migrations.RemoveField(
            model_name='stock_daily',
            name='name',
        ),
    ]
