# Generated by Django 3.2.19 on 2023-06-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20230621_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_daily',
            name='trade_date',
            field=models.DateField(blank=True, null=True, verbose_name='交易日期'),
        ),
    ]
