# Generated by Django 3.2.19 on 2024-03-01 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20240229_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='fund_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(db_index=True, max_length=16, verbose_name='代码')),
                ('name', models.CharField(max_length=32, verbose_name='指数名称')),
                ('management', models.CharField(max_length=32, verbose_name='管理人')),
                ('custodian', models.CharField(max_length=32, verbose_name='托管人')),
                ('fund_type', models.CharField(max_length=16, verbose_name='托管人')),
                ('found_date', models.DateField(blank=True, null=True, verbose_name='成立日期')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('list_date', models.DateField(blank=True, null=True, verbose_name='上市日期')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='发行日期')),
                ('issue_amount', models.FloatField(blank=True, null=True, verbose_name='发行份额(亿)')),
                ('m_fee', models.FloatField(blank=True, null=True, verbose_name='管理费')),
                ('c_fee', models.FloatField(blank=True, null=True, verbose_name='托管费')),
                ('duration_year', models.FloatField(blank=True, null=True, verbose_name='存续期')),
                ('p_value', models.FloatField(blank=True, null=True, verbose_name='面值')),
                ('min_amount', models.FloatField(blank=True, null=True, verbose_name='起点金额(万元)')),
                ('exp_return', models.FloatField(blank=True, null=True, verbose_name='预期收益率')),
                ('benchmark', models.CharField(blank=True, max_length=32, null=True, verbose_name='业绩比较基准')),
                ('status', models.CharField(blank=True, max_length=32, null=True, verbose_name='存续状态D摘牌 I发行 L已上市')),
                ('invest_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='投资风格')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='基金类型')),
                ('trustee', models.CharField(blank=True, max_length=32, null=True, verbose_name='受托人')),
                ('purc_startdate', models.CharField(blank=True, max_length=32, null=True, verbose_name='日常申购起始日')),
                ('redm_startdate', models.CharField(blank=True, max_length=32, null=True, verbose_name='日常赎回起始日')),
                ('market', models.CharField(blank=True, max_length=32, null=True, verbose_name='E场内O场外')),
                ('delist_date', models.DateField(blank=True, null=True, verbose_name='退市日期')),
            ],
        ),
        migrations.CreateModel(
            name='index_daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=16, verbose_name='代码')),
                ('trade_date', models.DateField(blank=True, null=True, verbose_name='交易日期')),
                ('turnover_rate', models.FloatField(blank=True, null=True, verbose_name='换手率（%）')),
                ('turnover_rate_f', models.FloatField(blank=True, null=True, verbose_name='换手率(基于自由流通股本)')),
                ('PE', models.FloatField(blank=True, null=True, verbose_name='市盈率')),
                ('PE_TTM', models.FloatField(blank=True, null=True, verbose_name='PE_TTM')),
                ('PB', models.FloatField(blank=True, null=True, verbose_name='PB')),
                ('float_share', models.FloatField(blank=True, null=True, verbose_name='流通股本(万股)')),
                ('circ_mv', models.FloatField(blank=True, null=True, verbose_name='流通市值（万元）')),
                ('total_share', models.FloatField(blank=True, null=True, verbose_name='总股本 （万股）')),
                ('total_mv', models.FloatField(blank=True, null=True, verbose_name='当日总市值（元）')),
                ('float_mv', models.FloatField(blank=True, null=True, verbose_name='当日流通股本（股）')),
            ],
        ),
        migrations.CreateModel(
            name='index_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(db_index=True, max_length=16, verbose_name='代码')),
                ('name', models.CharField(max_length=32, verbose_name='指数名称')),
                ('list_date', models.DateField(blank=True, null=True, verbose_name='上市日期')),
                ('industry', models.CharField(blank=True, max_length=1000, null=True, verbose_name='所属行业')),
                ('market', models.CharField(blank=True, max_length=1000, null=True, verbose_name='市场类型（主板/创业板/科创板/CDR）')),
                ('delist_date', models.DateField(blank=True, null=True, verbose_name='退市日期')),
            ],
        ),
        migrations.AddIndex(
            model_name='stock_daily',
            index=models.Index(fields=['ts_code', 'trade_date'], name='web_stock_d_ts_code_b53b62_idx'),
        ),
        migrations.AddField(
            model_name='index_daily',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.index_info'),
        ),
        migrations.AddIndex(
            model_name='index_daily',
            index=models.Index(fields=['ts_code', 'trade_date'], name='web_index_d_ts_code_26965d_idx'),
        ),
    ]
