# Generated by Django 3.2.19 on 2024-03-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20240301_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_info',
            name='name',
            field=models.CharField(max_length=256, verbose_name='指数名称'),
        ),
    ]
