# Generated by Django 3.2.19 on 2024-03-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_index_info_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_info',
            name='category',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='指数类别'),
        ),
        migrations.AlterField(
            model_name='index_info',
            name='fullname',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='指数全称'),
        ),
        migrations.AlterField(
            model_name='index_info',
            name='index_type',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='指数风格'),
        ),
        migrations.AlterField(
            model_name='index_info',
            name='publisher',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='发布方'),
        ),
    ]
