# Generated by Django 3.2.19 on 2024-03-01 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20240301_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index_daily',
            old_name='total_mv',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='index_daily',
            old_name='float_share',
            new_name='change',
        ),
        migrations.RenameField(
            model_name='index_daily',
            old_name='turnover_rate',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='index_daily',
            old_name='PE',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='index_daily',
            old_name='PE_TTM',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='index_daily',
            old_name='turnover_rate_f',
            new_name='open',
        ),
        migrations.RenameField(
            model_name='index_daily',
            old_name='circ_mv',
            new_name='pct_chg',
        ),
        migrations.RenameField(
            model_name='index_daily',
            old_name='PB',
            new_name='pre_close',
        ),
        migrations.RenameField(
            model_name='index_daily',
            old_name='total_share',
            new_name='vol',
        ),
        migrations.RemoveField(
            model_name='index_daily',
            name='float_mv',
        ),
        migrations.CreateModel(
            name='index_dailybasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=16, verbose_name='代码')),
                ('trade_date', models.DateField(blank=True, null=True, verbose_name='交易日期')),
                ('turnover_rate', models.FloatField(blank=True, null=True, verbose_name='换手率（%）')),
                ('turnover_rate_f', models.FloatField(blank=True, null=True, verbose_name='换手率(基于自由流通股本)')),
                ('PE', models.FloatField(blank=True, null=True, verbose_name='市盈率')),
                ('PE_TTM', models.FloatField(blank=True, null=True, verbose_name='PE_TTM')),
                ('PB', models.FloatField(blank=True, null=True, verbose_name='PB')),
                ('float_share', models.FloatField(blank=True, null=True, verbose_name='流通股本(万股)')),
                ('circ_mv', models.FloatField(blank=True, null=True, verbose_name='流通市值（万元）')),
                ('total_share', models.FloatField(blank=True, null=True, verbose_name='总股本 （万股）')),
                ('total_mv', models.FloatField(blank=True, null=True, verbose_name='当日总市值（元）')),
                ('float_mv', models.FloatField(blank=True, null=True, verbose_name='当日流通股本（股）')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.index_info')),
            ],
        ),
        migrations.AddIndex(
            model_name='index_dailybasic',
            index=models.Index(fields=['ts_code', 'trade_date'], name='web_index_d_ts_code_0bff16_idx'),
        ),
    ]
