# Generated by Django 3.2.19 on 2024-03-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20240301_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund_daily',
            name='name',
        ),
        migrations.RemoveField(
            model_name='index_daily',
            name='name',
        ),
        migrations.RemoveField(
            model_name='index_dailybasic',
            name='name',
        ),
    ]
