# Generated by Django 3.2.19 on 2024-03-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20240301_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_dailybasic',
            name='circ_mv',
        ),
        migrations.AddField(
            model_name='index_dailybasic',
            name='free_share',
            field=models.FloatField(blank=True, null=True, verbose_name='流通股本(万股)'),
        ),
    ]
