from django.db import models

# Create your models here.
'''class PeCompare(models.Model):
    ts_code = models.CharField(verbose_name="代码", max_length=16)
    name = models.CharField(verbose_name="股票名称", max_length=32)
    industry = models.CharField(verbose_name="行业", max_length=32)
    TTM = models.FloatField(verbose_name="PE TTM")
    LYR = models.FloatField(verbose_name="LYR")
    FORWARD = models.FloatField(verbose_name="FORWARD")
    netincome = models.FloatField(verbose_name="净利率")
    gross = models.FloatField(verbose_name="毛利率")
    CGR = models.FloatField(verbose_name="过去五年净利润复合增长率")
    amplitude = models.FloatField(verbose_name="年初至今涨辐")'''

class Balance(models.Model):
    """
    资产负债表
    """
    ts_code = models.CharField(verbose_name="代码", max_length=16)
    ann_date = models.DateField(null=True,blank=True)
    f_ann_date = models.DateField(verbose_name="公告期",null=True,blank=True)
    report_type = models.CharField(verbose_name="报表类型", max_length=32)
    comp_type = models.CharField(max_length=32,null=True,blank=True)
    end_type = models.CharField(verbose_name="报表类型", max_length=32,null=True,blank=True)
    end_date = models.DateField(null=True,blank=True)
    cap_rese = models.FloatField(verbose_name="资本公积金",null=True,blank=True)
    undistr_porfit = models.FloatField(verbose_name="未分配利润",null=True,blank=True)
    surplus_rese = models.FloatField(verbose_name="盈余公积金",null=True,blank=True)
    special_rese = models.FloatField(verbose_name="专项储备",null=True,blank=True)
    trad_asset = models.FloatField(verbose_name="交易性金融资产",null=True,blank=True)
    money_cap = models.FloatField(verbose_name="货币资金",null=True,blank=True)
    notes_receiv = models.FloatField(verbose_name="应收票据",null=True,blank=True)
    accounts_receiv = models.FloatField(verbose_name="应收账款",null=True,blank=True)
    oth_receiv = models.FloatField(verbose_name="其他应收款",null=True,blank=True)
    prepayment = models.FloatField(verbose_name="预付款项",null=True,blank=True)
    div_receiv = models.FloatField(verbose_name="应收股利",null=True,blank=True)
    int_receiv = models.FloatField(verbose_name="应收利息",null=True,blank=True)
    inventories = models.FloatField(verbose_name="存货",null=True,blank=True)
    amor_exp = models.FloatField(verbose_name="待摊费用",null=True,blank=True)
    total_share = models.FloatField(verbose_name="总股本",null=True,blank=True)
    nca_within_1y = models.FloatField(verbose_name="一年内到期的非流动资产",null=True,blank=True)
    sett_rsrv = models.FloatField(verbose_name="结算备付金",null=True,blank=True)
    loanto_oth_bank_fi = models.FloatField(verbose_name="拆出资金",null=True,blank=True)
    premium_receiv = models.FloatField(verbose_name="应收保费",null=True,blank=True)
    reinsur_receiv = models.FloatField(verbose_name="应收分保账款",null=True,blank=True)
    reinsur_res_receiv = models.FloatField(verbose_name="应收分保合同准备金",null=True,blank=True)
    pur_resale_fa = models.FloatField(verbose_name="买入返售金融资产",null=True,blank=True)
    oth_cur_assets = models.FloatField(verbose_name="其他流动资产",null=True,blank=True)
    total_cur_assets = models.FloatField(verbose_name="流动资产合计",null=True,blank=True)
    fa_avail_for_sale = models.FloatField(verbose_name="可供出售金融资产",null=True,blank=True)
    htm_invest = models.FloatField(verbose_name="持有至到期投资",null=True,blank=True)
    lt_eqt_invest = models.FloatField(verbose_name="长期股权投资",null=True,blank=True)
    invest_real_estate = models.FloatField(verbose_name="投资性房地产",null=True,blank=True)
    time_deposits = models.FloatField(verbose_name="定期存款",null=True,blank=True)
    oth_assets = models.FloatField(verbose_name="其他资产",null=True,blank=True)
    lt_rec = models.FloatField(verbose_name="长期应收款",null=True,blank=True)
    fix_assets = models.FloatField(verbose_name="固定资产",null=True,blank=True)
    cip = models.FloatField(verbose_name="在建工程",null=True,blank=True)
    const_materials = models.FloatField(verbose_name="工程物资",null=True,blank=True)
    fixed_assets_disp = models.FloatField(verbose_name="固定资产清理",null=True,blank=True)
    produc_bio_assets = models.FloatField(verbose_name="生产性生物资产",null=True,blank=True)
    oil_and_gas_assets = models.FloatField(verbose_name="油气资产",null=True,blank=True)
    intan_assets = models.FloatField(verbose_name="无形资产",null=True,blank=True)
    r_and_d = models.FloatField(verbose_name="研发支出",null=True,blank=True)
    goodwill = models.FloatField(verbose_name="商誉",null=True,blank=True)
    lt_amor_exp = models.FloatField(verbose_name="长期待摊费用",null=True,blank=True)
    defer_tax_assets = models.FloatField(verbose_name="递延所得税资产",null=True,blank=True)
    decr_in_disbur = models.FloatField(verbose_name="发放贷款及垫款",null=True,blank=True)
    oth_nca = models.FloatField(verbose_name="其他非流动资产",null=True,blank=True)
    total_nca = models.FloatField(verbose_name="非流动资产合计",null=True,blank=True)
    cash_reser_cb = models.FloatField(verbose_name="现金及存放中央银行款项",null=True,blank=True)
    depos_in_oth_bfi = models.FloatField(verbose_name="存放同业和其它金融机构款项",null=True,blank=True)
    prec_metals = models.FloatField(verbose_name="贵金属",null=True,blank=True)
    deriv_assets = models.FloatField(verbose_name="衍生金融资产",null=True,blank=True)
    rr_reins_une_prem = models.FloatField(verbose_name="应收分保未到期责任准备金",null=True,blank=True)
    rr_reins_outstd_cla = models.FloatField(verbose_name="应收分保未决赔款准备金",null=True,blank=True)
    rr_reins_lins_liab = models.FloatField(verbose_name="应收分保寿险责任准备金",null=True,blank=True)
    rr_reins_lthins_liab = models.FloatField(verbose_name="应收分保长期健康险责任准备金",null=True,blank=True)
    refund_depos = models.FloatField(verbose_name="存出保证金",null=True,blank=True)
    ph_pledge_loans = models.FloatField(verbose_name="保户质押贷款",null=True,blank=True)
    refund_cap_depos = models.FloatField(verbose_name="存出资本保证金",null=True,blank=True)
    indep_acct_assets = models.FloatField(verbose_name="独立账户资产",null=True,blank=True)
    client_depos = models.FloatField(verbose_name="其中：客户资金存款",null=True,blank=True)
    client_prov = models.FloatField(verbose_name="其中：客户备付金",null=True,blank=True)
    transac_seat_fee = models.FloatField(verbose_name="其中：交易席位费",null=True,blank=True)
    invest_as_receiv = models.FloatField(verbose_name="应收款项类投资",null=True,blank=True)
    total_assets = models.FloatField(verbose_name="资产总计",null=True,blank=True)
    lt_borr = models.FloatField(verbose_name="长期借款",null=True,blank=True)
    st_borr = models.FloatField(verbose_name="短期借款",null=True,blank=True)
    cb_borr = models.FloatField(verbose_name="向中央银行借款",null=True,blank=True)
    depos_ib_deposits = models.FloatField(verbose_name="吸收存款及同业存放",null=True,blank=True)
    loan_oth_bank = models.FloatField(verbose_name="拆入资金",null=True,blank=True)
    trading_fl = models.FloatField(verbose_name="交易性金融负债",null=True,blank=True)
    notes_payable = models.FloatField(verbose_name="应付票据",null=True,blank=True)
    acct_payable = models.FloatField(verbose_name="应付账款",null=True,blank=True)
    adv_receipts = models.FloatField(verbose_name="预收款项",null=True,blank=True)
    sold_for_repur_fa = models.FloatField(verbose_name="卖出回购金融资产款",null=True,blank=True)
    comm_payable = models.FloatField(verbose_name="应付手续费及佣金",null=True,blank=True)
    payroll_payable = models.FloatField(verbose_name="应付职工薪酬",null=True,blank=True)
    taxes_payable = models.FloatField(verbose_name="应交税费",null=True,blank=True)
    int_payable = models.FloatField(verbose_name="应付利息",null=True,blank=True)
    div_payable = models.FloatField(verbose_name="应付股利",null=True,blank=True)
    oth_payable = models.FloatField(verbose_name="其他应付款",null=True,blank=True)
    acc_exp = models.FloatField(verbose_name="预提费用",null=True,blank=True)
    deferred_inc = models.FloatField(verbose_name="递延收益",null=True,blank=True)
    st_bonds_payable = models.FloatField(verbose_name="应付短期债券",null=True,blank=True)
    payable_to_reinsurer = models.FloatField(verbose_name="应付分保账款",null=True,blank=True)
    rsrv_insur_cont = models.FloatField(verbose_name="保险合同准备金",null=True,blank=True)
    acting_trading_sec = models.FloatField(verbose_name="代理买卖证券款",null=True,blank=True)
    acting_uw_sec = models.FloatField(verbose_name="代理承销证券款",null=True,blank=True)
    non_cur_liab_due_1y = models.FloatField(verbose_name="一年内到期的非流动负债",null=True,blank=True)
    oth_cur_liab = models.FloatField(verbose_name="其他流动负债",null=True,blank=True)
    total_cur_liab = models.FloatField(verbose_name="流动负债合计",null=True,blank=True)
    bond_payable = models.FloatField(verbose_name="应付债券",null=True,blank=True)
    lt_payable = models.FloatField(verbose_name="长期应付款",null=True,blank=True)
    specific_payables = models.FloatField(verbose_name="专项应付款",null=True,blank=True)
    estimated_liab = models.FloatField(verbose_name="预计负债",null=True,blank=True)
    defer_tax_liab = models.FloatField(verbose_name="递延所得税负债",null=True,blank=True)
    defer_inc_non_cur_liab = models.FloatField(verbose_name="递延收益-非流动负债",null=True,blank=True)
    oth_ncl = models.FloatField(verbose_name="其他非流动负债",null=True,blank=True)
    total_ncl = models.FloatField(verbose_name="非流动负债合计",null=True,blank=True)
    depos_oth_bfi = models.FloatField(verbose_name="同业和其它金融机构存放款项",null=True,blank=True)
    deriv_liab = models.FloatField(verbose_name="衍生金融负债",null=True,blank=True)
    depos = models.FloatField(verbose_name="吸收存款",null=True,blank=True)
    agency_bus_liab = models.FloatField(verbose_name="代理业务负债",null=True,blank=True)
    oth_liab = models.FloatField(verbose_name="其他负债",null=True,blank=True)
    prem_receiv_adva = models.FloatField(verbose_name="预收保费",null=True,blank=True)
    depos_received = models.FloatField(verbose_name="存入保证金",null=True,blank=True)
    ph_invest = models.FloatField(verbose_name="保户储金及投资款",null=True,blank=True)
    reser_une_prem = models.FloatField(verbose_name="未到期责任准备金",null=True,blank=True)
    reser_outstd_claims = models.FloatField(verbose_name="未决赔款准备金",null=True,blank=True)
    reser_lins_liab = models.FloatField(verbose_name="寿险责任准备金",null=True,blank=True)
    reser_lthins_liab = models.FloatField(verbose_name="长期健康险责任准备金",null=True,blank=True)
    indept_acc_liab = models.FloatField(verbose_name="独立账户负债",null=True,blank=True)
    pledge_borr = models.FloatField(verbose_name="其中:质押借款",null=True,blank=True)
    indem_payable = models.FloatField(verbose_name="应付赔付款",null=True,blank=True)
    policy_div_payable = models.FloatField(verbose_name="应付保单红利",null=True,blank=True)
    total_liab = models.FloatField(verbose_name="负债合计",null=True,blank=True)
    treasury_share = models.FloatField(verbose_name="减:库存股",null=True,blank=True)
    ordin_risk_reser = models.FloatField(verbose_name="一般风险准备",null=True,blank=True)
    forex_differ = models.FloatField(verbose_name="	外币报表折算差额",null=True,blank=True)
    invest_loss_unconf = models.FloatField(verbose_name="未确认的投资损失",null=True,blank=True)
    minority_int = models.FloatField(verbose_name="少数股东权益",null=True,blank=True)
    total_hldr_eqy_exc_min_int = models.FloatField(verbose_name="股东权益合计(不含少数股东权益)",null=True,blank=True)
    total_hldr_eqy_inc_min_int = models.FloatField(verbose_name="股东权益合计(含少数股东权益)",null=True,blank=True)
    total_liab_hldr_eqy = models.FloatField(verbose_name="负债及股东权益总计",null=True,blank=True)
    lt_payroll_payable = models.FloatField(verbose_name="长期应付职工薪酬",null=True,blank=True)
    oth_comp_income = models.FloatField(verbose_name="其他综合收益",null=True,blank=True)
    oth_eqt_tools = models.FloatField(verbose_name="其他权益工具",null=True,blank=True)
    oth_eqt_tools_p_shr = models.FloatField(verbose_name="其他权益工具(优先股)",null=True,blank=True)
    lending_funds = models.FloatField(verbose_name="融出资金",null=True,blank=True)
    acc_receivable = models.FloatField(verbose_name="应收款项",null=True,blank=True)
    st_fin_payable = models.FloatField(verbose_name="应付短期融资款",null=True,blank=True)
    payables = models.FloatField(verbose_name="应付款项",null=True,blank=True)
    hfs_assets = models.FloatField(verbose_name="持有待售的资产",null=True,blank=True)
    hfs_sales = models.FloatField(verbose_name="持有待售的负债",null=True,blank=True)
    cost_fin_assets = models.FloatField(verbose_name="以摊余成本计量的金融资产",null=True,blank=True)
    fair_value_fin_assets = models.FloatField(verbose_name="以公允价值计量且其变动计入其他综合收益的金融资产",null=True,blank=True)
    cip_total = models.FloatField(verbose_name="在建工程(合计)(元)",null=True,blank=True)
    oth_pay_total = models.FloatField(verbose_name="其他应付款(合计)(元)",null=True,blank=True)
    long_pay_total = models.FloatField(verbose_name="长期应付款(合计)(元)",null=True,blank=True)
    debt_invest = models.FloatField(verbose_name="债权投资(元)",null=True,blank=True)
    oth_debt_invest = models.FloatField(verbose_name="其他债权投资(元)",null=True,blank=True)
    oth_eq_invest = models.FloatField(verbose_name="其他权益工具投资(元)",null=True,blank=True)
    oth_illiq_fin_assets = models.FloatField(verbose_name="其他非流动金融资产(元)",null=True,blank=True)
    oth_eq_ppbond = models.FloatField(verbose_name="其他权益工具:永续债(元)",null=True,blank=True)
    receiv_financing = models.FloatField(verbose_name="应收款项融资",null=True,blank=True)
    use_right_assets = models.FloatField(verbose_name="使用权资产",null=True,blank=True)
    lease_liab = models.FloatField(verbose_name="租赁负债",null=True,blank=True)
    contract_assets = models.FloatField(verbose_name="合同资产",null=True,blank=True)
    contract_liab = models.FloatField(verbose_name="合同负债",null=True,blank=True)
    accounts_receiv_bill = models.FloatField(verbose_name="应收票据及应收账款",null=True,blank=True)
    accounts_pay = models.FloatField(verbose_name="应付票据及应付账款",null=True,blank=True)
    oth_rcv_total = models.FloatField(verbose_name="其他应收款(合计)（元）",null=True,blank=True)
    fix_assets_total = models.FloatField(verbose_name="固定资产(合计)(元)",null=True,blank=True)
    update_flag = models.CharField(verbose_name="更新标识", max_length=2)

class Income(models.Model):
    """
    利润表
    """
    ts_code = models.CharField(verbose_name="代码", max_length=16)
    ann_date = models.DateField(null=True,blank=True)
    f_ann_date = models.DateField(verbose_name="公告期",null=True,blank=True)
    report_type = models.CharField(verbose_name="报表类型", max_length=32)
    comp_type = models.CharField(max_length=32,null=True,blank=True)
    end_type = models.CharField(verbose_name="报表类型", max_length=32,null=True,blank=True)
    end_date = models.DateField(null=True,blank=True)
    basic_eps = models.FloatField(verbose_name="基本每股收益",null=True,blank=True)
    diluted_eps = models.FloatField(verbose_name="稀释每股收益",null=True,blank=True)
    total_revenue = models.FloatField(verbose_name="营业总收入",null=True,blank=True)
    revenue = models.FloatField(verbose_name="营业收入",null=True,blank=True)
    int_income = models.FloatField(verbose_name="利息收入",null=True,blank=True)
    prem_earned = models.FloatField(verbose_name="已赚保费",null=True,blank=True)
    comm_income = models.FloatField(verbose_name="手续费及佣金收入",null=True,blank=True)
    n_commis_income = models.FloatField(verbose_name="手续费及佣金净收入",null=True,blank=True)
    n_oth_income = models.FloatField(verbose_name="其他经营净收益",null=True,blank=True)
    n_oth_b_income = models.FloatField(verbose_name="加:其他业务净收益",null=True,blank=True)
    prem_income = models.FloatField(verbose_name="保险业务收入",null=True,blank=True)
    out_prem = models.FloatField(verbose_name="减:分出保费",null=True,blank=True)
    une_prem_reser = models.FloatField(verbose_name="提取未到期责任准备金",null=True,blank=True)
    reins_income = models.FloatField(verbose_name="其中:分保费收入",null=True,blank=True)
    n_sec_tb_income = models.FloatField(verbose_name="代理买卖证券业务净收入",null=True,blank=True)
    n_sec_uw_income = models.FloatField(verbose_name="证券承销业务净收入",null=True,blank=True)
    n_asset_mg_income = models.FloatField(verbose_name="受托客户资产管理业务净收入",null=True,blank=True)
    oth_b_income = models.FloatField(verbose_name="其他业务收入",null=True,blank=True)
    fv_value_chg_gain = models.FloatField(verbose_name="加:公允价值变动净收益",null=True,blank=True)
    invest_income = models.FloatField(verbose_name="加:投资净收益",null=True,blank=True)
    ass_invest_income = models.FloatField(verbose_name="其中:对联营企业和合营企业的投资收益",null=True,blank=True)
    forex_gain = models.FloatField(verbose_name="加:汇兑净收益",null=True,blank=True)
    total_cogs = models.FloatField(verbose_name="营业总成本",null=True,blank=True)
    oper_cost = models.FloatField(verbose_name="减:营业成本",null=True,blank=True)
    int_exp = models.FloatField(verbose_name="减:利息支出",null=True,blank=True)
    comm_exp = models.FloatField(verbose_name="减:手续费及佣金支出",null=True,blank=True)
    biz_tax_surchg = models.FloatField(verbose_name="减:营业税金及附加",null=True,blank=True)
    sell_exp = models.FloatField(verbose_name="	减:销售费用",null=True,blank=True)
    admin_exp = models.FloatField(verbose_name="减:管理费用",null=True,blank=True)
    fin_exp = models.FloatField(verbose_name="减:财务费用",null=True,blank=True)
    assets_impair_loss = models.FloatField(verbose_name="减:资产减值损失",null=True,blank=True)
    prem_refund = models.FloatField(verbose_name="退保金",null=True,blank=True)
    compens_payout = models.FloatField(verbose_name="赔付总支出",null=True,blank=True)
    reser_insur_liab = models.FloatField(verbose_name="提取保险责任准备金",null=True,blank=True)
    div_payt = models.FloatField(verbose_name="保户红利支出",null=True,blank=True)
    reins_exp = models.FloatField(verbose_name="分保费用",null=True,blank=True)
    oper_exp = models.FloatField(verbose_name="营业支出",null=True,blank=True)
    compens_payout_refu = models.FloatField(verbose_name="减:摊回赔付支出",null=True,blank=True)
    insur_reser_refu = models.FloatField(verbose_name="减:摊回保险责任准备金",null=True,blank=True)
    reins_cost_refund = models.FloatField(verbose_name="减:摊回分保费用",null=True,blank=True)
    other_bus_cost = models.FloatField(verbose_name="其他业务成本",null=True,blank=True)
    operate_profit = models.FloatField(verbose_name="营业利润",null=True,blank=True)
    non_oper_income = models.FloatField(verbose_name="加:营业外收入",null=True,blank=True)
    non_oper_exp = models.FloatField(verbose_name="减:营业外支出",null=True,blank=True)
    nca_disploss = models.FloatField(verbose_name="其中:减:非流动资产处置净损失",null=True,blank=True)
    total_profit = models.FloatField(verbose_name="利润总额",null=True,blank=True)
    income_tax = models.FloatField(verbose_name="所得税费用",null=True,blank=True)
    n_income = models.FloatField(verbose_name="净利润(含少数股东损益)",null=True,blank=True)
    n_income_attr_p = models.FloatField(verbose_name="净利润(不含少数股东损益)",null=True,blank=True)
    minority_gain = models.FloatField(verbose_name="少数股东损益",null=True,blank=True)
    oth_compr_income = models.FloatField(verbose_name="其他综合收益",null=True,blank=True)
    t_compr_income = models.FloatField(verbose_name="综合收益总额",null=True,blank=True)
    compr_inc_attr_p = models.FloatField(verbose_name="归属于母公司(或股东)的综合收益总额",null=True,blank=True)
    compr_inc_attr_m_s = models.FloatField(verbose_name="归属于少数股东的综合收益总额",null=True,blank=True)
    ebit = models.FloatField(verbose_name="息税前利润",null=True,blank=True)
    ebitda = models.FloatField(verbose_name="息税折旧摊销前利润",null=True,blank=True)
    insurance_exp = models.FloatField(verbose_name="保险业务支出",null=True,blank=True)
    undist_profit = models.FloatField(verbose_name="年初未分配利润",null=True,blank=True)
    distable_profit = models.FloatField(verbose_name="可分配利润",null=True,blank=True)
    rd_exp = models.FloatField(verbose_name="研发费用",null=True,blank=True)
    fin_exp_int_exp = models.FloatField(verbose_name="财务费用:利息费用",null=True,blank=True)
    fin_exp_int_inc = models.FloatField(verbose_name="财务费用:利息收入",null=True,blank=True)
    transfer_surplus_rese = models.FloatField(verbose_name="盈余公积转入",null=True,blank=True)
    transfer_housing_imprest = models.FloatField(verbose_name="住房周转金转入",null=True,blank=True)
    transfer_oth = models.FloatField(verbose_name="其他转入",null=True,blank=True)
    adj_lossgain = models.FloatField(verbose_name="调整以前年度损益",null=True,blank=True)
    withdra_legal_surplus = models.FloatField(verbose_name="提取法定盈余公积",null=True,blank=True)
    withdra_legal_pubfund = models.FloatField(verbose_name="提取法定公益金",null=True,blank=True)
    withdra_biz_devfund = models.FloatField(verbose_name="提取企业发展基金",null=True,blank=True)
    withdra_rese_fund = models.FloatField(verbose_name="提取储备基金",null=True,blank=True)
    withdra_oth_ersu = models.FloatField(verbose_name="提取任意盈余公积金",null=True,blank=True)
    workers_welfare = models.FloatField(verbose_name="职工奖金福利",null=True,blank=True)
    distr_profit_shrhder = models.FloatField(verbose_name="可供股东分配的利润",null=True,blank=True)
    prfshare_payable_dvd = models.FloatField(verbose_name="应付优先股股利",null=True,blank=True)
    comshare_payable_dvd = models.FloatField(verbose_name="应付普通股股利",null=True,blank=True)
    capit_comstock_div = models.FloatField(verbose_name="转作股本的普通股股利",null=True,blank=True)
    net_after_nr_lp_correct = models.FloatField(verbose_name="扣除非经常性损益后的净利润（更正前）",null=True,blank=True)
    credit_impa_loss = models.FloatField(verbose_name="信用减值损失",null=True,blank=True)
    net_expo_hedging_benefits = models.FloatField(verbose_name="净敞口套期收益",null=True,blank=True)
    oth_impair_loss_assets = models.FloatField(verbose_name="其他资产减值损失",null=True,blank=True)
    total_opcost = models.FloatField(verbose_name="营业总成本（二）",null=True,blank=True)
    amodcost_fin_assets = models.FloatField(verbose_name="以摊余成本计量的金融资产终止确认收益",null=True,blank=True)
    oth_income = models.FloatField(verbose_name="其他收益",null=True,blank=True)
    asset_disp_income = models.FloatField(verbose_name="资产处置收益",null=True,blank=True)
    continued_net_profit = models.FloatField(verbose_name="持续经营净利润",null=True,blank=True)
    end_net_profit = models.FloatField(verbose_name="终止经营净利润",null=True,blank=True)
    update_flag = models.CharField(verbose_name="更新标识",max_length=2,null=True,blank=True)

class Cashflow(models.Model):
    """
    现金流量表
    """
    ts_code = models.CharField(verbose_name="代码", max_length=16)
    ann_date = models.DateField(null=True,blank=True)
    f_ann_date = models.DateField(verbose_name="公告期",null=True,blank=True)
    report_type = models.CharField(verbose_name="报表类型", max_length=32)
    comp_type = models.CharField(max_length=32,null=True,blank=True)
    end_type = models.CharField(verbose_name="报表类型", max_length=32,null=True,blank=True)
    end_date = models.DateField(null=True,blank=True)
    net_profit = models.FloatField(verbose_name="净利润",null=True,blank=True)
    finan_exp = models.FloatField(verbose_name="财务费用",null=True,blank=True)
    c_fr_sale_sg = models.FloatField(verbose_name="销售商品、提供劳务收到的现金",null=True,blank=True)
    recp_tax_rends = models.FloatField(verbose_name="收到的税费返还",null=True,blank=True)
    n_depos_incr_fi = models.FloatField(verbose_name="客户存款和同业存放款项净增加额",null=True,blank=True)
    n_incr_loans_cb = models.FloatField(verbose_name="向中央银行借款净增加额",null=True,blank=True)
    n_inc_borr_oth_fi = models.FloatField(verbose_name="向其他金融机构拆入资金净增加额",null=True,blank=True)
    prem_fr_orig_contr = models.FloatField(verbose_name="收到原保险合同保费取得的现金",null=True,blank=True)
    n_incr_insured_dep = models.FloatField(verbose_name="保户储金净增加额",null=True,blank=True)
    n_reinsur_prem = models.FloatField(verbose_name="收到再保业务现金净额",null=True,blank=True)
    n_incr_disp_tfa = models.FloatField(verbose_name="处置交易性金融资产净增加额",null=True,blank=True)
    ifc_cash_incr = models.FloatField(verbose_name="收取利息和手续费净增加额",null=True,blank=True)
    n_incr_disp_faas = models.FloatField(verbose_name="处置可供出售金融资产净增加额",null=True,blank=True)
    n_incr_loans_oth_bank = models.FloatField(verbose_name="拆入资金净增加额",null=True,blank=True)
    n_cap_incr_repur = models.FloatField(verbose_name="回购业务资金净增加额",null=True,blank=True)
    c_fr_oth_operate_a = models.FloatField(verbose_name="收到其他与经营活动有关的现金",null=True,blank=True)
    c_inf_fr_operate_a = models.FloatField(verbose_name="经营活动现金流入小计",null=True,blank=True)
    c_paid_goods_s = models.FloatField(verbose_name="购买商品、接受劳务支付的现金",null=True,blank=True)
    c_paid_to_for_empl = models.FloatField(verbose_name="支付给职工以及为职工支付的现金",null=True,blank=True)
    c_paid_for_taxes = models.FloatField(verbose_name="支付的各项税费",null=True,blank=True)
    n_incr_clt_loan_adv = models.FloatField(verbose_name="客户贷款及垫款净增加额",null=True,blank=True)
    n_incr_dep_cbob = models.FloatField(verbose_name="存放央行和同业款项净增加额",null=True,blank=True)
    c_pay_claims_orig_inco = models.FloatField(verbose_name="支付原保险合同赔付款项的现金",null=True,blank=True)
    pay_handling_chrg = models.FloatField(verbose_name="支付手续费的现金",null=True,blank=True)
    pay_comm_insur_plcy = models.FloatField(verbose_name="支付保单红利的现金",null=True,blank=True)
    oth_cash_pay_oper_act = models.FloatField(verbose_name="支付其他与经营活动有关的现金",null=True,blank=True)
    st_cash_out_act = models.FloatField(verbose_name="经营活动现金流出小计",null=True,blank=True)
    n_cashflow_act = models.FloatField(verbose_name="经营活动产生的现金流量净额",null=True,blank=True)
    oth_recp_ral_inv_act = models.FloatField(verbose_name="经营活动产生的现金流量净额",null=True,blank=True)
    c_disp_withdrwl_invest = models.FloatField(verbose_name="收回投资收到的现金",null=True,blank=True)
    c_recp_return_invest = models.FloatField(verbose_name="取得投资收益收到的现金",null=True,blank=True)
    n_recp_disp_fiolta = models.FloatField(verbose_name="处置固定资产、无形资产和其他长期资产收回的现金净额",null=True,blank=True)
    n_recp_disp_sobu = models.FloatField(verbose_name="处置子公司及其他营业单位收到的现金净额",null=True,blank=True)
    stot_inflows_inv_act = models.FloatField(verbose_name="投资活动现金流入小计",null=True,blank=True)
    c_pay_acq_const_fiolta = models.FloatField(verbose_name="购建固定资产、无形资产和其他长期资产支付的现金",null=True,blank=True)
    c_paid_invest = models.FloatField(verbose_name="投资支付的现金",null=True,blank=True)
    n_disp_subs_oth_biz = models.FloatField(verbose_name="取得子公司及其他营业单位支付的现金净额",null=True,blank=True)
    oth_pay_ral_inv_act = models.FloatField(verbose_name="支付其他与投资活动有关的现金",null=True,blank=True)
    n_incr_pledge_loan = models.FloatField(verbose_name="质押贷款净增加额",null=True,blank=True)
    stot_out_inv_act = models.FloatField(verbose_name="投资活动现金流出小计",null=True,blank=True)
    n_cashflow_inv_act = models.FloatField(verbose_name="投资活动产生的现金流量净额",null=True,blank=True)
    c_recp_borrow = models.FloatField(verbose_name="取得借款收到的现金",null=True,blank=True)
    proc_issue_bonds = models.FloatField(verbose_name="发行债券收到的现金",null=True,blank=True)
    oth_cash_recp_ral_fnc_act = models.FloatField(verbose_name="收到其他与筹资活动有关的现金",null=True,blank=True)
    stot_cash_in_fnc_act = models.FloatField(verbose_name="筹资活动现金流入小计",null=True,blank=True)
    free_cashflow = models.FloatField(verbose_name="企业自由现金流量",null=True,blank=True)
    c_prepay_amt_borr = models.FloatField(verbose_name="偿还债务支付的现金",null=True,blank=True)
    c_pay_dist_dpcp_int_exp = models.FloatField(verbose_name="分配股利、利润或偿付利息支付的现金",null=True,blank=True)
    incl_dvd_profit_paid_sc_ms = models.FloatField(verbose_name="其中:子公司支付给少数股东的股利、利润",null=True,blank=True)
    oth_cashpay_ral_fnc_act = models.FloatField(verbose_name="支付其他与筹资活动有关的现金",null=True,blank=True)
    stot_cashout_fnc_act = models.FloatField(verbose_name="筹资活动现金流出小计",null=True,blank=True)
    n_cash_flows_fnc_act = models.FloatField(verbose_name="筹资活动产生的现金流量净额",null=True,blank=True)
    eff_fx_flu_cash = models.FloatField(verbose_name="汇率变动对现金的影响",null=True,blank=True)
    n_incr_cash_cash_equ = models.FloatField(verbose_name="现金及现金等价物净增加额",null=True,blank=True)
    c_cash_equ_beg_period = models.FloatField(verbose_name="期初现金及现金等价物余额",null=True,blank=True)
    c_cash_equ_end_period = models.FloatField(verbose_name="期末现金及现金等价物余额",null=True,blank=True)
    c_recp_cap_contrib = models.FloatField(verbose_name="吸收投资收到的现金",null=True,blank=True)
    incl_cash_rec_saims = models.FloatField(verbose_name="吸收投资收到的现金",null=True,blank=True)
    uncon_invest_loss = models.FloatField(verbose_name="未确认投资损失",null=True,blank=True)
    prov_depr_assets = models.FloatField(verbose_name="加:资产减值准备",null=True,blank=True)
    depr_fa_coga_dpba = models.FloatField(verbose_name="固定资产折旧、油气资产折耗、生产性生物资产折旧",null=True,blank=True)
    amort_intang_assets = models.FloatField(verbose_name="无形资产摊销",null=True,blank=True)
    lt_amort_deferred_exp = models.FloatField(verbose_name="长期待摊费用摊销",null=True,blank=True)
    decr_deferred_exp = models.FloatField(verbose_name="待摊费用减少",null=True,blank=True)
    incr_acc_exp = models.FloatField(verbose_name="预提费用增加",null=True,blank=True)
    loss_disp_fiolta = models.FloatField(verbose_name="处置固定、无形资产和其他长期资产的损失",null=True,blank=True)
    loss_scr_fa = models.FloatField(verbose_name="固定资产报废损失",null=True,blank=True)
    loss_fv_chg = models.FloatField(verbose_name="公允价值变动损失",null=True,blank=True)
    invest_loss = models.FloatField(verbose_name="投资损失",null=True,blank=True)
    decr_def_inc_tax_assets = models.FloatField(verbose_name="递延所得税资产减少",null=True,blank=True)
    incr_def_inc_tax_liab = models.FloatField(verbose_name="递延所得税负债增加",null=True,blank=True)
    decr_inventories = models.FloatField(verbose_name="存货的减少",null=True,blank=True)
    decr_oper_payable = models.FloatField(verbose_name="经营性应收项目的减少",null=True,blank=True)
    incr_oper_payable = models.FloatField(verbose_name="经营性应付项目的增加",null=True,blank=True)
    others = models.FloatField(verbose_name="其他",null=True,blank=True)
    im_net_cashflow_oper_act = models.FloatField(verbose_name="经营活动产生的现金流量净额(间接法)",null=True,blank=True)
    conv_debt_into_cap = models.FloatField(verbose_name="债务转为资本",null=True,blank=True)
    conv_copbonds_due_within_1y = models.FloatField(verbose_name="一年内到期的可转换公司债券",null=True,blank=True)
    fa_fnc_leases = models.FloatField(verbose_name="融资租入固定资产",null=True,blank=True)
    im_n_incr_cash_equ = models.FloatField(verbose_name="现金及现金等价物净增加额(间接法)",null=True,blank=True)
    net_dism_capital_add = models.FloatField(verbose_name="拆出资金净增加额",null=True,blank=True)
    net_cash_rece_sec = models.FloatField(verbose_name="代理买卖证券收到的现金净额(元)",null=True,blank=True)
    credit_impa_loss = models.FloatField(verbose_name="信用减值损失",null=True,blank=True)
    use_right_asset_dep = models.FloatField(verbose_name="使用权资产折旧",null=True,blank=True)
    oth_loss_asset = models.FloatField(verbose_name="其他资产减值损失",null=True,blank=True)
    end_bal_cash = models.FloatField(verbose_name="现金的期末余额",null=True,blank=True)
    beg_bal_cash = models.FloatField(verbose_name="减:现金的期初余额",null=True,blank=True)
    end_bal_cash_equ = models.FloatField(verbose_name="加:现金等价物的期末余额",null=True,blank=True)
    beg_bal_cash_equ = models.FloatField(verbose_name="减:现金等价物的期初余额",null=True,blank=True)
    update_flag = models.FloatField(verbose_name="更新标志(1最新）",null=True,blank=True)

class stock_daily(models.Model):
    """
    股票每日价格，
    """
    ts_code = models.CharField(verbose_name="代码", max_length=16)
    trade_date = models.DateField(verbose_name="交易日期", null=True,blank=True)
    open = models.FloatField(verbose_name="当日开盘价",null=True,blank=True)
    close = models.FloatField(verbose_name="当日收盘价",null=True,blank=True)
    high = models.FloatField(verbose_name="当日最高价",null=True,blank=True)
    low = models.FloatField(verbose_name="当日最低价",null=True,blank=True)
    change = models.FloatField(verbose_name="涨跌额",null=True,blank=True)
    pct_chg = models.FloatField(verbose_name="涨跌幅",null=True,blank=True)
    vol = models.FloatField(verbose_name="成交量（手）",null=True,blank=True)
    amount = models.FloatField(verbose_name="成交额（千元）",null=True,blank=True)
    turnover_rate = models.FloatField(verbose_name="换手率（%）",null=True,blank=True)
    pre_close = models.FloatField(verbose_name="昨收价(前复权)",null=True,blank=True)
    PE_TTM = models.FloatField(verbose_name="PE_TTM",null=True,blank=True)
    PB = models.FloatField(verbose_name="PB",null=True,blank=True)
    float_share = models.FloatField(verbose_name="流通股本(万股)",null=True,blank=True)
    circ_mv = models.FloatField(verbose_name="流通市值（万元）",null=True,blank=True)
    total_share = models.FloatField(verbose_name="总股本 （万股）",null=True,blank=True)
    total_mv = models.FloatField(verbose_name="总市值 （万元）",null=True,blank=True)


class stock_info(models.Model):
    """
    股票的基本信息
    """
    ts_code = models.CharField(verbose_name="代码", max_length=16)
    name = models.CharField(verbose_name="股票名称", max_length=32)
    list_date = models.DateField(verbose_name="上市日期", null=True, blank=True)
    industry = models.CharField(verbose_name="所属行业", null=True, blank=True, max_length=1000)
    market = models.CharField(verbose_name="市场类型（主板/创业板/科创板/CDR）", null=True, blank=True, max_length=1000)
    delist_date = models.DateField(verbose_name="退市日期", null=True, blank=True)


